//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StockMasterWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class ScriptData
    {
        public long Id { get; set; }
        public string Code { get; set; }
        public System.DateTime tDate { get; set; }
        public decimal tOpen { get; set; }
        public decimal tHigh { get; set; }
        public decimal tLow { get; set; }
        public decimal tClose { get; set; }
        public long Volume { get; set; }
        public decimal EMA9 { get; set; }
        public decimal EMA21 { get; set; }
        public string tCall { get; set; }
        public string tStatus { get; set; }
        public decimal tEntry { get; set; }
        public decimal tExit { get; set; }
        public int LotSize { get; set; }
    }
}
